export const GalleryData = [
    {
        id:1,
        titile:"nails",
        
        image:"./images/n1.png"
    },
    {
        id:2,
        titile:"nails",
        image:"./images/n2.png"
    },
    {
        id:3,
        titile:"nails",
        image:"./images/n3.png"
    },
    {
        id:4,
        titile:"nails",
        image:"./images/n4.png"
    },
    {
        id:5,
        titile:"paraffine",
        image:"./images/b1.png"
    },
    {
        id:6,
        titile:"paraffine",
        image:"./images/b2.png"
    },
    {
        id:7,
        titile:"Hydarafacial",
        image:"./images/s1.png"
    },
    {
        id:8,
        titile:"Hydarafacial",
        image:"./images/s2.png"
    },
    {
        id:9,
        titile:"bodycare",
        image:"./images/s3.png"
    },
    {
        id:10,
        titile:"massage",
        image:"./images/s4.png"
    },
    {
        id:11,
        titile:"massage",
        image:"./images/s5.png"
    },
    {
        id:12,
        titile:"massage",
        image:"./images/s6.png"
    },
    {
        id:13,
        titile:"hair",
        image:"./images/h1.png"
    },
    {
        id:14,
        titile:"hair",
        image:"./images/h2.png"
    },
    {
        id:15,
        titile:"hair",
        image:"./images/h3.png"
    },
    {
        id:16,
        titile:"hair",
        image:"./images/h4.png"
    },
    {
        id:17,
        titile:"hair",
        image:"./images/h5.png"
    },
]